openapi: 3.1.0
info:
  title: Chinook RestAPI
  version: 1.0.0

paths:
  /top_selling_albums:
    get:
      summary: Get top-selling albums
      description: Returns the top 10 selling albums within a specified datetime range.
      x-af-database: chinook
      x-af-sql: >
        SELECT
            a.album_id as album_id,
            a.title AS album_title,
            COUNT(il.invoice_line_id) AS total_sold
        FROM
            invoice_line il
        JOIN
            track t ON il.track_id = t.track_id
        JOIN
            album a ON t.album_id = a.album_id
        WHERE
            i.invoice_date >= :start
            AND i.invoice_date <= :end
        GROUP BY
            a.title
        ORDER BY
            total_sold DESC
        LIMIT :limit;
      parameters:
        - in: query
          name: start
          schema:
            type: string
            format: date-time
          required: true
          description: Start datetime for the sales period.
        - in: query
          name: end
          schema:
            type: string
            format: date-time
          required: true
          description: End datetime for the sales period.
        - in: query
          name: limit
          schema:
            type: integer
          default: 10
          description: The number of albums to return.
      responses:
        '200':
          description: A list of top-selling albums
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    album_id:
                      type: integer
                      description: The id of the album
                    album_title:
                      type: string
                      description: The title of the album
                    total_sold:
                      type: integer
                      description: The number of albums sold
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /top_selling_albums_rename:
    get:
      summary: Get top-selling albums
      description: Returns the top 10 selling albums within a specified datetime range.
      x-af-database: chinook
      x-af-sql: >
        SELECT
            a.album_id,
            a.title,
            COUNT(il.invoice_line_id) AS total_sold
        FROM
            invoice_line il
        JOIN invoice i ON
            il.invoice_id = i.invoice_id
        JOIN
            track t ON il.track_id = t.track_id
        JOIN
            album a ON t.album_id = a.album_id
        WHERE
            i.invoice_date >= :start
            AND i.invoice_date <= :end
        GROUP BY
            a.album_id
        ORDER BY
            total_sold DESC
        LIMIT :limit
      parameters:
        - in: query
          name: start
          schema:
            type: string
            format: date-time
          required: true
          description: Start datetime for the sales period.
        - in: query
          name: end
          schema:
            type: string
            format: date-time
          required: true
          description: End datetime for the sales period.
        - in: query
          name: limit
          schema:
            type: integer
          default: 10
          description: The number of albums to return.
      responses:
        '200':
          description: A list of top-selling albums
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    album_id:
                      type: integer
                      description: The id of the album
                      x-af-column-name: a.album_id
                    album_title:
                      type: string
                      description: The title of the album
                      x-af-column-name: a.title
                    total_sold:
                      type: integer
                      description: The number of albums sold
        '400':
          description: Invalid input
        '500':
          description: Internal server error


components:
  schemas:
    album:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        album_id:
          type: integer
          x-af-primary-key: auto
        title:
          type: string
          maxLength: 160
        artist_id:
          type: integer
      required:
        - album_id
        - title
        - artist_id
    artist:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        artist_id:
          type: integer
          x-af-primary-key: auto
        name:
          type: string
          maxLength: 120
      required:
        - artist_id
    customer:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      x-af-concurrency-control: version_stamp
      properties:
        customer_id:
          type: integer
          x-af-primary-key: auto
        first_name:
          type: string
          maxLength: 40
        last_name:
          type: string
          maxLength: 20
        company:
          type: string
          maxLength: 80
        address:
          type: string
          maxLength: 70
        city:
          type: string
          maxLength: 40
        state:
          type: string
          maxLength: 40
        country:
          type: string
          maxLength: 40
        postal_code:
          type: string
          maxLength: 10
        phone:
          type: string
          maxLength: 24
        fax:
          type: string
          maxLength: 24
        email:
          type: string
          maxLength: 60
        support_rep_id:
          type: integer
        version_stamp:
          type: string
      required:
        - customer_id
        - first_name
        - last_name
        - email
    Employee:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        employee_id:
          type: integer
          x-af-primary-key: auto
        last_name:
          type: string
          maxLength: 20
        first_name:
          type: string
          maxLength: 20
        title:
          type: string
          maxLength: 30
        reports_to:
          type: integer
        birth_date:
          type: string
          format: date-time
        hire_date:
          type: string
          format: date-time
        address:
          type: string
          maxLength: 70
        city:
          type: string
          maxLength: 40
        state:
          type: string
          maxLength: 40
        country:
          type: string
          maxLength: 40
        postal_code:
          type: string
          maxLength: 10
        phone:
          type: string
          maxLength: 24
        fax:
          type: string
          maxLength: 24
        email:
          type: string
          maxLength: 60
      required:
        - employee_id
        - last_name
        - first_name
    Genre:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        genre_id:
          type: integer
          x-af-primary-key: auto
        name:
          type: string
          maxLength: 120
      required:
        - genre_id
    invoice:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      x-af-concurrency-control: last_updated
      properties:
        invoice_id:
          type: integer
          x-af-primary-key: auto
        customer_id:
          type: integer
        customer:
          $ref: '#/components/schemas/customer'
          x-af-parent-property: customer_id
        invoice_date:
          type: string
          format: date-time
        billing_address:
          type: string
          maxLength: 70
        billing_city:
          type: string
          maxLength: 40
        billing_state:
          type: string
          maxLength: 40
        billing_country:
          type: string
          maxLength: 40
        billing_postal_code:
          type: string
          maxLength: 10
        line_items:
          type: array
          items:
            $ref: "#/components/schemas/invoice_line"
            x-af-child-property: invoice_id
        total:
          type: number
          format: float
        last_updated:
          type: string
          format: date-time
      required:
        - invoice_id
        - customer_id
        - invoice_date
        - total
    invoice_line:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        invoice_line_id:
          type: integer
          x-af-primary-key: auto
        invoice_id:
          type: integer
        track_id:
          type: integer
        unit_price:
          type: number
          format: float
        quantity:
          type: integer
      required:
        - invoice_line_id
        - invoice_id
        - track_id
        - unit_price
        - quantity
    media_type:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        media_type_id:
          type: integer
          x-af-primary-key: auto
        name:
          type: string
          maxLength: 120
      required:
        - media_type_id
    playlist:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        playlist_id:
          type: integer
          x-af-primary-key: auto
        name:
          type: string
          maxLength: 120
      required:
        - playlist_id
    playlist_track:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        playlist_id:
          type: integer
        track_id:
          type: integer
      required:
        - playlist_id
        - track_id
    track:
      type: object
      x-af-engine: postgres
      x-af-database: chinook
      properties:
        track_id:
          type: integer
          x-af-primary-key: auto
        name:
          type: string
          maxLength: 200
        album_id:
          type: integer
        media_type_id:
          type: integer
        genre_id:
          type: integer
        composer:
          type: string
          maxLength: 220
        milliseconds:
          type: integer
        bytes:
          type: integer
        unit_price:
          type: number
          format: float
      required:
        - track_id
        - name
        - media_type_id
        - milliseconds
        - unit_price
