
ALTER TABLE customer
  ADD COLUMN version_stamp UUID DEFAULT uuid_generate_v4() NOT NULL;

ALTER TABLE invoice
  ADD COLUMN last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE genre
  ADD COLUMN version INT NOT NULL DEFAULT 1;
